# Generated by Django 2.2.4 on 2019-10-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('androidApis', '0003_auto_20191022_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='claims',
            field=models.IntegerField(default=0),
        ),
    ]
