# Generated by Django 2.2.4 on 2019-09-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('androidApis', '0002_car_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField()),
                ('raisedAt', models.DateTimeField()),
                ('settledAt', models.DateTimeField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfInsurance', models.DateField()),
                ('monthlyPremium', models.FloatField()),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(default='User', on_delete=django.db.models.deletion.CASCADE, to='androidApis.Customer'),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('transactionId', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='androidApis.Car')),
                ('insurance', models.ForeignKey(default='Transactions', on_delete=django.db.models.deletion.CASCADE, to='androidApis.Insurance')),
            ],
        ),
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictedAt', models.DateTimeField()),
                ('predictedPrice', models.FloatField()),
                ('actualPrice', models.FloatField()),
                ('claim', models.ForeignKey(default='Predictions', on_delete=django.db.models.deletion.CASCADE, to='androidApis.Claims')),
            ],
        ),
        migrations.AddField(
            model_name='insurance',
            name='car',
            field=models.ForeignKey(default='Insurance', on_delete=django.db.models.deletion.CASCADE, to='androidApis.Car'),
        ),
        migrations.AddField(
            model_name='claims',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='androidApis.Insurance'),
        ),
    ]
