# Generated by Django 2.2.4 on 2019-09-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('androidApis', '0003_auto_20190904_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='uid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
